name: Bazel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /path/to/your/dependencies
          key: bazel-${{ runner.workspace }}-${{ hashFiles('WORKSPACE.bazel') }}

      - name: Build
        run: bazel build //...

      - name: Test execution
        run: bazel run //mlua_example:mlua_example
